#python read_new.py img_show_1_dark train_1dark
#python read_new.py img_show_2_dark train_2dark
#python read_new.py img_show_3_dark train_3dark
#python read_new.py img_show_4_dark train_4dark
#python read_new.py img_show_5_dark train_5dark
#python read_new.py img_show_6_dark train_6dark
#python read_new.py img_show_7_dark train_7dark
#python read_new.py img_test_sirt train_2dark
python read_new.py img_show/spd40_80_2 spd40_80
python read_new.py img_show/spd70_80_2 spd70_80